### ISSUE TITLE
Add gpg-agent option to extend passphrase timeout?

### ISSUE THREAD

**Issue by thewaywest** [Baggykiin/pass-winmenu#23]
I am happy with a longer time before the passphrase must be reentered. This is a command-line parameter for gpg-agent and I _think_ it is is set using the **--default-cache-ttl** option, defaulting to 600 seconds.

I only use gpg-agent for pass-winmenu right now. I am manually starting the gpg-agent so I can set my own values, but it would be great to have access to that through your config file.

Thoughts?

**update**
Finally located the gpg-agent.conf in C:\Users\<username>\AppData\Roaming\gnupg. Windows search on C: hadn't located it for some reason.

I added a line to my file:

> ###+++--- GPGConf ---+++###
> ###+++--- GPGConf ---+++### 11/10/17 12:50:24 Romance Standard Time
> GPGConf edited this configuration file.
> #It will disable options before this marked block, but it will
> #never change anything below these lines.
> default-cache-ttl 7200

Then confirmed it was set using PowerShell (or CMD):
PS > gpgconf --list-options gpg-agent

> Monitor:1:0:Options controlling the diagnostic output:0:0::::
> verbose:12:0:verbose:0:0::::
> quiet:8:0:be somewhat more quiet:0:0::::
> Configuration:1:0:Options controlling the configuration:0:0::::
> disable-scdaemon:8:1:do not use the SCdaemon:0:0::::
> enable-ssh-support:0:0:enable ssh support:0:0::::
> ssh-fingerprint-digest:24:2:use ALGO to show ssh fingerprints:1:1:ALGO:"md5::
> enable-putty-support:0:0:enable putty support:0:0::::
> enable-extended-key-format:8:3::0:0::::
> Debug:1:1:Options useful for debugging:0:0::::
> debug-level:26:1:set the debugging level to LEVEL:1:1:LEVEL:"none::
> log-file:8:1:write server mode logs to FILE:32:1:FILE:::
> Security:1:0:Options controlling the security:0:0::::
> **default-cache-ttl:24:0:expire cached PINs after N seconds:3:3:N:600::7200**
> default-cache-ttl-ssh:24:1:expire SSH keys after N seconds:3:3:N:1800::

**Comment by Baggykiin** [comment]
I've considered this a while back. Currently I just have a manually created `gpg-agent.conf` file with those settings in it, but it would be nicer if pass-winmenu could manage this as well.

As you mentioned, the location of the config file is normally in `AppData\Roaming\gnupg`, although this can be altered by setting the `GNUPGHOME` environment variable.

This means pass-winmenu will first need to check which location GPG will use, so it knows where to look for the `gpg-agent.conf` file. It might be possible to query GPG in order to find out which path it will use as home directory, that way we wouldn't have to resort to guessing.

When it comes to actually implementing this feature, I think the best way to do that would probably to create a config section in `pass-winmenu.yaml` in which users can manually enter `gpg-agent.conf` options. Something like this:

```
gpg-agent:
    config:
        # Set this to true to allow pass-winmenu to set some configuration keys in your
        # `gpg-agent.conf` file, allowing you to configure some features like password timeout.
        allow-config-management: true
        keys:
            # Remember your master password for up to one hour.
            # Every time you decrypt a password within this one-hour timespan, the timer will reset.
            default-cache-ttl: 7200
            # This is the maximum amount of time gpg-agent will remember your master password.
            # Once this amount of time has expired, gpg-agent will always ask you to re-enter it.
            max-cache-ttl: 127800

```

To prevent pass-winmenu from messing with config files when you might not want it to, this feature would be disabled by default (`allow-config-management` would be set to `false`).
